<a href="https://colab.research.google.com/github/jyothisriprabhakargit/machine_learning_and_data_science/blob/main/ML_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy assignment**

*1.Import numpy*

In [1]:
import numpy as np

*2.Create an array of 10 zeros*

In [2]:
np.zeros ((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

*3.Create an array of 10 ones*

In [3]:
np.ones ((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

*4.Create an array of 10 fives*

In [4]:
np.ones (10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

*5.Create an array of integer from 11 to 50*

In [5]:
np.random.randint(11, 50)

12

In [6]:
np.arange(11, 50)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])

*6.Create an array of all the even integer from 11 to 50*

In [7]:
np.arange(11,50,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

*7.Create a 3 * 3 matrices of value from range 0 to 8*

In [8]:

np.arange (0,9). reshape (3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

*8.Using numpy to generate a number randomly between 0 and 1*

In [9]:
np.random.normal(0, 1,1)

array([0.19092551])

In [10]:
np.random.normal()

1.7051383793274568

**Create the following matrices**

*20 linrarly spaced point between 0 and 2*

In [11]:
np.linspace(0, 2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

**Numpy indexing and selection**

In [12]:
mat=np.arange(1, 26).reshape(5, 5) 
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

*1.Only first value of matrices mat*

In [13]:
mat. item(0)

1

*2.Middle value of matrices mat*

In [14]:
mat[2][2]

13

*3.First two rows and last one column value of matrices mat*

In [15]:
Y=mat[0:1]
X=mat[:,-1]
print(Y)

print(X)

[[1 2 3 4 5]]
[ 5 10 15 20 25]


In [16]:
mat[0:2,4]

array([ 5, 10])

*4.Last row and all column values of matrices mat*

In [17]:
Y=mat[4:5]
print(Y)

[[21 22 23 24 25]]


In [18]:
mat[4:, :]

array([[21, 22, 23, 24, 25]])